version: '3'
services:
  app:
    build:
      context: .
      args:
        NPM_COMMAND: dev
        NPM_OMIT: ''
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: app
    expose:
      - '3000'
    ports:
      - '3060:3000'