version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add: [SYS_ADMIN, DAC_READ_SEARCH]
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    env_file: .env
    ports:
      - '3060:3000'