version: '3'
services:
  app:
    build:
      context: .
      args:
        NPM_OMIT: ''
      dockerfile: Dockerfile
    cap_add: [SYS_ADMIN, DAC_READ_SEARCH]
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    env_file: .env
    container_name: app
    expose:
      - '3000'
    ports:
      - '3060:3000'

networks:
  backend:
    driver: bridge